ALWADI/Models/Doctor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;

#nullable disable

namespace ALWADI.Models
{
    public partial class Doctor
    {

        public Doctor()
        {

            Appointments = new HashSet<Appointment>();
        }

        public int DoctorId { get; set; }
       // [Required(ErrorMessage = "هذا الحقل اجباري")]

        [Display(Name="اسم الطبيب")]
        
        public string DoctorName { get; set; }
       // [Required(ErrorMessage = "هذا الحقل اجباري")]
        
        [Display(Name = "رقم الطبيب")]

        public string DoctorPhone { get; set; }
      //  [Required(ErrorMessage = "هذا الحقل اجباري")]

        [Display(Name = "ايميل الطبيب")]

        public string DoctorEmail { get; set; }
       // [Required(ErrorMessage = "هذا الحقل اجباري")]

        [Display(Name = "عنوان الطبيب")]

        public string DoctorAddrress { get; set; }
        [Display(Name = "عنوان العيادة")]
        public int clincLocation { get; set; }
       // [Required(ErrorMessage = "هذا الحقل اجباري")]

        [Display(Name = "جنس الطبيب")]

        public string DoctorGender { get; set; }

        [Display(Name = "اختصاص الطبيب")]

        public string DoctorSpecialization { get; set; }

        [Display(Name = "الكشفية")]
       

        public int? CostPerPatient { get; set; }

        [Display(Name = "الشهادة")]

        public string DoctorCertificate { get; set; }

        [Display(Name = "سنوات الخبرة")]

        public int? WorkExperience { get; set; }

        [Display(Name = "صورة الطبيب")]
        //[Required (ErrorMessage ="هذا الحقل اجباري")]
        public byte[] DoctorImg { get; set; }

        [Display(Name = "القسم")]

        public int? DepartmentNum { get; set; }
        [Display(Name = "كلفة حجز الموعد")]

        public double? reversedCost { set; get; }
        [Display(Name = "الوصف")]
        public string? Descreption { get; set; }


        public ICollection<DoctorSpecialization> doctorSpecializations { get; set; }
        

        public virtual Department DepartmentNumNavigation { get; set; }
        public virtual Location clincLocationNavigation { get; set; }

        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}

ALWADI/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ALWADI.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace ALWADI.Controllers
{
    // [Authorize]
    public class DoctorsController : Controller
    {
        private readonly AL_WADIContext _context;

        public DoctorsController(AL_WADIContext context)
        {
            _context = context;
        }
        public IActionResult EditImg(int id, [FromForm] IFormFile Img)
        {
            var doctor = _context.Doctors.Where(i => i.DoctorId == id).FirstOrDefault();
            //doctor.DoctorImg = Img;
            if (Img != null)
            {
                foreach (var file in Request.Form.Files)
                {


                    MemoryStream ms = new MemoryStream();
                    file.CopyTo(ms);
                    doctor.DoctorImg = ms.ToArray();

                    ms.Close();
                    ms.Dispose();



                }
                _context.Update(doctor);
                _context.SaveChangesAsync();
            }
            return Json(new { doctor = doctor });

        }


        public JsonResult Getspec(int depId)
        {
            var listspec = _context.Specializations.Where(x => x.DepNum == depId).ToList();

            return Json(listspec);
        }

        // GET: Doctors
        public async Task<IActionResult> Index()
        {
            var aL_WADIContext = _context.Doctors.Include(d => d.DepartmentNumNavigation).Include(l => l.clincLocationNavigation);

            return View(await aL_WADIContext.ToListAsync());
        }


        // GET: Doctors/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            ViewBag.avg = getDoctorAppoitments(id);

            var doctor = await _context.Doctors
                .Include(d => d.DepartmentNumNavigation)
                .FirstOrDefaultAsync(m => m.DoctorId == id);
            var doctorspec = _context.DoctorSpecializations.Where(s => s.Did == id).Include(s => s.Specialization);
            ViewBag.sp = doctorspec;
            if (doctor.DoctorImg != null)
            {

                string imageBase64Data =
    Convert.ToBase64String(doctor.DoctorImg);
                string imageDataURL =
            string.Format("data:image/jpg;base64,{0}",
            imageBase64Data);
                //ViewBag.ImageTitle = img.ImageTitle;
                ViewBag.ImageDataUrl = imageDataURL;
            }

           


            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // GET: Doctors/Create
        public IActionResult Create()
        {
            ViewData["DepartmentNum"] = new SelectList(_context.Departments, "DepartmentId", "DepartmentName");

            ViewData["DoctorSpecialization"] = new SelectList(_context.Specializations, "SpecializationId", "SpecializationName");

            ViewData["location"] = new SelectList(_context.Locations, "Id", "location");

            return View();
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DoctorId,DoctorName,DoctorPhone,DoctorEmail,DoctorAddrress,DoctorGender,DoctorSpecialization,CostPerPatient,DoctorCertificate,WorkExperience,DoctorImg,DepartmentNum,clincLocation,reversedCost,Descreption")] Doctor doctor, List<int> spId)
        {
            if (ModelState.IsValid)
            {


                if (doctor != null)
                {
                    foreach (var file in Request.Form.Files)
                    {


                        MemoryStream ms = new MemoryStream();
                        file.CopyTo(ms);
                        doctor.DoctorImg = ms.ToArray();

                        ms.Close();
                        ms.Dispose();



                    }
                }
                doctor.DoctorSpecialization = "-";
                //var speclization = _context.Specializations.Find(Convert.ToInt32(doctor.DoctorSpecialization));
                //doctor.DoctorSpecialization = speclization.SpecializationName;
                // doctor.reversedCost = 0;
                if (doctor.Descreption == null)
                {
                    doctor.Descreption = "-";
                }
                _context.Add(doctor);
                await _context.SaveChangesAsync();

                foreach (var item in spId)
                {
                    DoctorSpecialization doctorSpecialization = new DoctorSpecialization()
                    {
                        Cid = item,
                        Did = doctor.DoctorId,
                        Specialization = _context.Specializations.Where(x => x.SpecializationId == item).FirstOrDefault(),
                        Doctor = doctor
                    };
                    _context.DoctorSpecializations.Add(doctorSpecialization);
                    _context.SaveChanges();
                }
               // _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentNum"] = new SelectList(_context.Departments, "DepartmentId", "DepartmentName", doctor.DepartmentNum);
            ViewData["location"] = new SelectList(_context.Locations, "Id", "location", doctor.clincLocation);

            return View(doctor);
        }


        // GET: Doctors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctor =  _context.Doctors.Where(i=>i.DoctorId==id).FirstOrDefault(); 

            if (doctor == null)
            {
                return NotFound();
            }
            ViewData["location"] = new SelectList(_context.Locations, "Id", "location",doctor.clincLocation );

            ViewData["DepartmentNum"] = new SelectList(_context.Departments, "DepartmentId", "DepartmentName", doctor.DepartmentNum);
            return View(doctor);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DoctorId,DoctorName,DoctorPhone,DoctorEmail,DoctorAddrress,DoctorGender,DoctorSpecialization,CostPerPatient,DoctorCertificate,WorkExperience,DepartmentNum,clincLocation,reversedCost,Descreption")] Doctor doctor, IFormFile DoctorImg)
        {
            if (id != doctor.DoctorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (DoctorImg != null)
                    {
                        foreach (var file in Request.Form.Files)
                        {


                            MemoryStream ms = new MemoryStream();
                            file.CopyTo(ms);
                           doctor.DoctorImg = ms.ToArray();

                            ms.Close();
                            ms.Dispose();



                        }
                        _context.Update(doctor);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        var existingDoctor = _context.Doctors.Find(id);
                       // doctor.DoctorImg=existingDoctor.DoctorImg;
                        existingDoctor.clincLocation = doctor.clincLocation;
                        existingDoctor.DoctorGender = doctor.DoctorGender;
                        existingDoctor.DoctorCertificate = doctor.DoctorCertificate;
                        existingDoctor.DoctorPhone = doctor.DoctorPhone;
                        existingDoctor.DoctorEmail = doctor.DoctorEmail;
                        existingDoctor.DepartmentNum = doctor.DepartmentNum;
                        existingDoctor.DoctorAddrress = doctor.DoctorAddrress;
                       // existingDoctor.DoctorImg = doctor.DoctorImg;
                        existingDoctor.DoctorName = doctor.DoctorName;
                        existingDoctor.DoctorSpecialization = doctor.DoctorSpecialization;
                        existingDoctor.reversedCost = doctor.reversedCost;
                        existingDoctor.WorkExperience = doctor.WorkExperience;
                        existingDoctor.CostPerPatient = doctor.CostPerPatient;
                        existingDoctor.Descreption=doctor.Descreption;
                        _context.Update(existingDoctor);
                        await _context.SaveChangesAsync();
                    }
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoctorExists(doctor.DoctorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentNum"] = new SelectList(_context.Departments, "DepartmentId", "DepartmentName", doctor.DepartmentNum);
            return View(doctor);
        }

        // GET: Doctors/Delete/5

ALWADI/Views/Doctors/Delete.cshtml
@model ALWADI.Models.Doctor

@{
    ViewData["Title"] = "Delete";
}



@*<h3 style="margin-top:10px;"></h3>*@

<div class="row">
    <div class="col-12">

        <div class="card card-danger border-0">
            <div class="card-header">
                <h3 class="card-title">هل أنت متأكد من حذف المعلومات التالية؟</h3>


                <div class="d-inline">
                    <a asp-action="Index"><i class="fa fa-arrow-left fa-lg"></i> </a>
                </div>

            </div>

            <form asp-action="Delete">
                <input type="hidden" asp-for="DoctorId" />
                <div class="card-body">
                    <div class="row justify-content-center">
                        <div class="col-5">
                            <div class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="DoctorName" class="control-label">@Html.DisplayNameFor(model => model.DoctorName)</label>
                                <input asp-for="DoctorName" class="form-control" />
                                <span asp-validation-for="DoctorName" class="text-danger"></span>
                            </div>


                            <div class="form-group">
                                <label asp-for="DoctorAddrress" class="control-label">@Html.DisplayNameFor(model => model.DoctorAddrress)</label>
                                <input asp-for="DoctorAddrress" class="form-control" />
                                <span asp-validation-for="DoctorAddrress" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="DoctorPhone" class="control-label">@Html.DisplayNameFor(model => model.DoctorPhone)</label>
                                <input asp-for=" DoctorPhone" class="form-control" />
                                <span asp-validation-for="DoctorPhone" class="text-danger"></span>
                            </div>
                            <div class="form-group ">
                                <label asp-for="DoctorEmail" class="control-label"> @Html.DisplayNameFor(model => model.DoctorEmail)</label>
                                <input asp-for="DoctorEmail" class="form-control" />
                                <span asp-validation-for="DoctorEmail" class="text-danger"></span>
                            </div>




                        </div>
                        <div class="col-5">

                            <div class="form-group">
                                <label asp-for="DoctorGender" class="control-label">@Html.DisplayNameFor(model => model.DoctorGender)</label>
                                <input asp-for="DoctorGender" class="form-control" />
                                <span asp-validation-for="DoctorGender" class="text-danger"></span>
                            </div>

                           
                            <div class="form-group">
                                <label asp-for="DoctorCertificate" class="control-label">@Html.DisplayNameFor(model => model.DoctorCertificate)</label>
                                <input asp-for="DoctorCertificate" class="form-control" />
                                <span asp-validation-for="DoctorCertificate" class="text-danger"></span>
                            </div>
                            <div class="form-group ">
                                <label asp-for="WorkExperience" class="control-label"> @Html.DisplayNameFor(model => model.WorkExperience)</label>
                                <input asp-for="WorkExperience" class="form-control" />
                                <span asp-validation-for="WorkExperience" class="text-danger"></span>
                            </div>
                            @*<div class="form-group ">
                                <label asp-for="DoctorImg" class="control-label"> @Html.DisplayNameFor(model => model.DoctorImg)</label>
                                <input asp-for="DoctorImg" class="form-control" />
                                <span asp-validation-for="DoctorImg" class="text-danger"></span>
                            </div>*@





                        </div>

                    

                        @*<div class="form-group ">
                            <label asp-for="DoctorSpecialization" class="control-label"> @Html.DisplayNameFor(model => model.DoctorSpecialization)</label>
                            <input asp-for="DoctorSpecialization" class="form-control" />
                            <span asp-validation-for="DoctorSpecialization" class="text-danger"></span>
                        </div>*@

                    </div>
                </div>
                <div class="card-footer">
                   
                    <input type="submit" value="حذف" class="btn btn-danger" />
                </div>
            </form>

        </div>
    </div>
</div>

ALWADI/Views/Doctors/DoctorLogin.cshtml
@model ALWADI.Models.Doctor


@{ Layout = null; }
<!DOCTYPE html>
<html>
<head>

    <link rel="icon" href="~/images/logo.png">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AL-WADI</title>

    <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css">
    <link href="~/AdminStyle/css/styles.css" asp-append-version="true" rel="stylesheet" />

</head>
<body>
    @using (Html.BeginForm("DoctorProfile", "Doctors"))
    {
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                                    <div class="card-body">
                                        <form id="account" method="get">
                                            <div asp-validation-summary="All" class="text-danger"></div>
                                            <div class="form-floating mb-3">
                                                <label asp-for="DoctorName" style="float:left;"></label>
                                                <input asp-for="DoctorName" class="form-control" name="name" placeholder="اسم الطبيب" />

                                            </div>
                                            <div class="form-floating mb-3 ">
                                                <label asp-for="DoctorPhone" style="float:left;"></label>
                                                <input asp-for="DoctorPhone" class="form-control" placeholder="رقم الموبايل" name="phone" />

                                                <span asp-validation-for="DoctorPhone" class="text-danger"></span>
                                            </div>
                                            @*<div class="form-check mb-3">
                                                    <label class="form-check-label" asp-for="Input.RememberMe" style="float:left;">
                                                        <input class="form-check-input" type="checkbox" asp-for="Input.RememberMe" />
                                                        &nbsp;&nbsp;
                                                        @Html.DisplayNameFor(m => m.Input.RememberMe)
                                                    </label>
                                                </div>*@
                                            <div class="d-flex align-items-center  mt-4 mb-0  d-flex justify-content-center">

                                                <button type="submit" class="btn btn-primary " @*asp-route-id="@Model.DoctorId" asp-action="DoctorAppointment1"*@>Login</button>
                                            </div>
                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
        </div>
        }
    </body>

</html>

ALWADI/Views/Doctors/DoctorProfile.cshtml
@model IEnumerable<ALWADI.Models.AppointmentGet>

@{Layout =null;}




<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AL-WADI</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" />
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.39.0/css/tempusdominus-bootstrap-4.min.css" />
    <!-- iCheck -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/icheck-bootstrap/3.0.1/icheck-bootstrap.min.css" />
    <!-- JQVMap -->
    <!-- Theme style -->
    <link href="~/dist/css/adminlte.min.css" rel="stylesheet" />
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/overlayscrollbars/1.13.1/css/OverlayScrollbars.min.css" />
    <!-- Daterange picker -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <!-- summernote -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.18/summernote-bs4.min.css" />
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- Bootstrap 4 RTL -->
    <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css">
    @*
        <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap4.min.css">*@
    <!-- Custom style for RTL -->
    <link rel="stylesheet" href="~/css/custom.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.3/css/buttons.dataTables.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" asp-append-version="true" href="~/css/site.css" />


    <style>
        tbody {
            font-family: 'Arabic Typesetting';
            font-size: x-large;
        }

        thead {
            white-space: nowrap;
            color: red;
            font-family: 'Arabic Typesetting';
            font-size: x-large;
        }
    </style>

</head>

<body>
    <div class="card-header">
        @using (Html.BeginForm("Search", "Doctors"))
        {



            <div class="container">
                <div class="row">


                    <div class="col">

                        <input type="date" id="birthday" name="date" class=" form-control">
                    </div>

                    <div class="col">
                        @*<input type="submit" class=" justify-content-center ">*@
                        <button class="btn" style="color:cornflowerblue;">بحث<i class="fa fa-search" style="color:cornflowerblue;"></i></button>
                    </div>


                    <div class="col">
                        @if (ViewBag.name != null)
                        {

                            <input type="hidden" class=" form-control" name="keywords" placeholder="search" value="@ViewBag.name" />


                        }
                    </div>
                </div>

            </div>

        }

    </div>

    <div class="card-body">
        <div class="table-responsive">



            <table class="table table-striped" id="dep_table">
                <thead>
                    <tr>
                        <th style="text-align: center;">
                            @Html.DisplayNameFor(model => model.DepartmentName)
                        </th>

                        <th style="text-align: center;">
                            @Html.DisplayNameFor(model => model.DoctorName)
                        </th>
                        <th style="text-align: center;">
                            @Html.DisplayNameFor(model => model.PatientName)
                        </th>
                        <th style="text-align: center;">
                            @Html.DisplayNameFor(model => model.Date)
                        </th>



                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td style="text-align: center;">
                                @item.DepartmentName
                            </td>
                            <td style="text-align: center;">
                                @item.DoctorName
                            </td>
                            <td style="text-align: center;">
                                @item.PatientName
                            </td>
                            <td style="text-align: center;">
                                @item.Date
                            </td>

                        </tr>
                    }
                </tbody>
            </table>


        </div>
    </div>

    <div class="card-footer">
        <div class="col col-md-6 ">
            <button type="button" id="export_button" class="btn btn-success btn-sm">Export</button>
        </div>
    </div>
    @section Scripts {
        <script>
            $(function () {
                $('#dep_table').DataTable({

                    "lengthMenu": [[5, 10, 15, 20, 25, -1], [5, 10, 15, 20, 25, "All"]],
                    "responsive": true,
                    "autoWidth": true,
                    "filter": false,

                    "language": {
                        "sProcessing": "جارٍ التحميل...",
                        "sLengthMenu": "أظهر _MENU_ مدخلات",
                        "sZeroRecords": "لم يتم العثور على أية نتائج",
                        "sInfo": "إظهار _START_ إلى _END_ من أصل _TOTAL_ مدخل",
                        "sInfoEmpty": "يعرض 0 إلى 0 من أصل 0 سجل",
                        "sInfoFiltered": "(منتقاة من مجموع _MAX_ مُدخل)",
                        "sInfoPostFix": "",
                        /*"sSearch": "البحث:",*/
                        "sUrl": "",
                        "oPaginate": {
                            "sFirst": "الأول",
                            "sPrevious": "السابق",
                            "sNext": "التالي",
                            "sLast": "الأخير"
                        }
                    }
                });
            });



            function html_table_to_excel(type) {
                var data = document.getElementById('dep_table');

                var file = XLSX.utils.table_to_book(data, { sheet: "sheet1" });

                XLSX.write(file, { bookType: type, bookSST: true, type: 'base64' });

                XLSX.writeFile(file, 'file.' + type);
            }

            const export_button = document.getElementById('export_button');

            export_button.addEventListener('click', () => {
                html_table_to_excel('xlsx');
            });


        </script>

    }

</body>
</html>